version: '3'
services:
  db:
    image: postgres:13
    container_name: projectmanager_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projectmanager
    ports:
      - "5432:5432"